spring:
  application:
    name: CET_CELL

  datasource:
    url: YOUR_DATABASE_URL
    username: YOUR_USERNAME
    password: YOUR_PASSWORD

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

 