spring:
  application:
    name: veloxdiag-server

  datasource:
    url: jdbc:mysql://hayabusa.proxy.rlwy.net:17602/railway
    username: root
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true